### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 12345
}
### Cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "99c7f79f7c20486591d9ed06a307b2c2",
  "accountNumber": "1000000002",
  "amount": 12345
}